// Aggregate scraped/*.json → src/data/accounts-full.json
// Run after validate. Real data only — no dummy/fallback.
// Accounts with no scrape file are skipped (visible in summary).
// V16: also inject `account.localAvatar` if a real photo file exists in
// assets/avatars/{slug}.{ext} — generated by scrape-avatars.mjs.
import 'dotenv/config';
import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { ALL_ACCOUNTS } from './accounts.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SCRAPED_DIR = path.join(__dirname, 'scraped');
const OUT_DIR = path.join(__dirname, '..', 'src', 'data');
const AVATAR_DIR = path.join(__dirname, '..', 'assets', 'avatars');
const AVATAR_EXTS = ['.jpg', '.jpeg', '.webp', '.png'];

/**
 * If a real photo file exists for this slug in assets/avatars/, return the
 * public path. Otherwise null (caller leaves `localAvatar` undefined so the
 * UI falls back to the brand-icon tile).
 */
async function findLocalAvatar(slug) {
  for (const ext of AVATAR_EXTS) {
    const avatarPath = path.join(AVATAR_DIR, `${slug}${ext}`);
    try {
      await fs.access(avatarPath);
      return `/TITAN/assets/avatars/${slug}${ext}`;
    } catch {}
  }
  return null;
}

async function main() {
  await fs.mkdir(OUT_DIR, { recursive: true });

  // Pre-flight: fail fast kalau scraped/ ada backup files (defense in depth).
  // Bug yang sama dengan validate-merge.mjs line 120 — kalau scraped/*.backup-*.json
  // lolos, generate-data bisa overwrite post legitimate dengan data stale dari backup.
  const scrapedAll = await fs.readdir(SCRAPED_DIR);
  const backups = scrapedAll.filter((f) => f.includes('.backup-') && f.endsWith('.json'));
  if (backups.length > 0) {
    console.error(`❌ Found ${backups.length} backup file(s) in scraped/:`);
    backups.forEach((f) => console.error(`   - ${f}`));
    console.error(`   Move them out of scraped/ or delete them. Backup files in scraped/ break SSOT.`);
    process.exit(1);
  }

  const allData = [];
  const missing = [];

  for (const acc of ALL_ACCOUNTS) {
    const scrapedPath = path.join(SCRAPED_DIR, `${acc.slug}.json`);
    let data = null;
    try {
      data = JSON.parse(await fs.readFile(scrapedPath, 'utf-8'));
      console.log(`✅ ${acc.slug} — ${data.posts?.length ?? 0} posts`);
    } catch {
      missing.push(acc.slug);
      console.warn(`⚠️  ${acc.slug} — no scrape file, skipped`);
      continue;
    }

    data.account.slug = data.account.slug ?? acc.slug;
    data.account.username = data.account.username ?? acc.username;

    // V16: inject localAvatar if a real photo file is committed to the repo
    const localAvatar = await findLocalAvatar(acc.slug);
    if (localAvatar) {
      data.account.localAvatar = localAvatar;
    } else {
      delete data.account.localAvatar; // ensure stale value is cleared
    }

    allData.push(data);
  }

  const outPath = path.join(OUT_DIR, 'accounts-full.json');
  await fs.writeFile(outPath, JSON.stringify(allData, null, 2));
  const totalPosts = allData.reduce((s, a) => s + (a.posts?.length ?? 0), 0);
  const withLocalAvatar = allData.filter((a) => a.account.localAvatar).length;
  console.log(`\n=== GENERATE COMPLETE ===`);
  console.log(`Output: ${outPath}`);
  console.log(`Real accounts: ${allData.length}/${ALL_ACCOUNTS.length}`);
  console.log(`Total posts: ${totalPosts}`);
  console.log(`Local avatars: ${withLocalAvatar}/${allData.length}`);
  if (missing.length > 0) {
    console.log(`Missing (no real data): ${missing.join(', ')}`);
  }

  // Post-write validation: defense in depth against future regressions
  // (validate-merge.mjs line 120 bug emptied scraped/ → generate-data wrote 0 post).
  const verify = JSON.parse(await fs.readFile(outPath, 'utf-8'));
  if (verify.length !== 9) {
    throw new Error(`Post-write: expected 9 accounts, got ${verify.length}`);
  }
  const verifyTotalPosts = verify.reduce((s, a) => s + (a.posts?.length ?? 0), 0);
  // V29.1: lower threshold from 4000 to 3500. SSOT pre-dedup was 4134 (with 453 in-file
  // duplicate records per shortcode, 2 ID formats coexisting). After V29 composite-key
  // dedup, expected ~3705 (24 unique posts gained from scraped/, 429 redundant dup
  // removed). 3500 is the new defense-in-depth floor — buffer of ~200 below expected.
  // See plan peppy-discovering-cherny.md for V29.1 audit.
  if (verifyTotalPosts < 3500) {
    throw new Error(`Post-write: post count ${verifyTotalPosts} < 3500 (likely data loss)`);
  }
  const seenKeys = new Map();
  let crossDup = 0;
  for (const a of verify) {
    for (const p of a.posts || []) {
      const key = p.shortcode || p.id;
      if (!key) continue;
      if (seenKeys.has(key) && seenKeys.get(key) !== a.account.slug) {
        crossDup++;
      } else {
        seenKeys.set(key, a.account.slug);
      }
    }
  }
  if (crossDup > 0) {
    // Tolerance untuk data historis: cross-account dup bisa terjadi kalau 1 post
    // di-share/embed di multiple akun (e.g. ig-syahfalahproperti re-post ig-ardiantanah).
    // Batas 5 dup = wajar untuk dataset historis. Kalau naik → investigate.
    if (crossDup <= 5) {
      console.warn(`⚠️  Post-write: ${crossDup} cross-account duplicate(s) detected (within tolerance, see DATA-SSOT.md §4)`);
    } else {
      throw new Error(`Post-write: ${crossDup} cross-account duplicate(s) detected (exceeds tolerance of 5)`);
    }
  }
  console.log(`\n✅ Post-write validation passed (9 akun, ${verifyTotalPosts} posts, 0 cross-dup)`);
}

main().catch((err) => {
  console.error('Fatal error:', err);
  process.exit(1);
});
